kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mypvc
  namespace: default
  annotations:
    ibm.io/auto-create-bucket: "false"
    ibm.io/auto-delete-bucket: "false"
    ibm.io/bucket: "parser"
    # ibm.io/object-path: ""
    ibm.io/secret-name: "cos-write-access"
    ibm.io/endpoint: "https://s3.us-south.cloud-object-storage.appdomain.cloud"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi # Enter a fictitious value
  storageClassName: ibmc-s3fs-standard-regional
