# cos-write-access
apiVersion: v1
data:
  api-key: {{ .Values.credential.apikey | b64enc }} 
  service-instance-id: {{ .Values.credential.guid | b64enc}}
kind: Secret
metadata:
  name: cos-write-access
type: ibm/ibmc-s3fs
